version: '3'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - ./utiles/conectar.py:/code/.

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: bonos_db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: santa
      MYSQL_PASSWORD: admin
    volumes:
      - bonos_volume:/var/lib/mysql

volumes:
  bonos_volume:
